filebeat.inputs:
- type: filestream
  id: coverage
  paths:
    - /mnt/coverage/*.json
  parsers:
    - ndjson:
      overwrite_keys: true
      add_error_key: true
      expand_keys: true



# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true


# processors:
#  - add_docker_metadata: ~


setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}


output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
